name: 添加建议
description: 🆕 建议将某内容添加到列表中
title: '[ADDITION] <标题>'
labels: ['建议添加', '等待审核']
assignees:
  - lissy93
body:
  # 位置
  - type: input
    id: location
    attributes:
      label: 位置
      description: >-
        请指出应添加内容的章节（如适用，还需注明子章节）
      placeholder:
    validations:
      required: true

  # 添加内容信息
  - type: textarea
    id: addition
    attributes:
      label: 添加内容
      description: |
        请描述应添加的内容
        如有必要，请提供权威来源的链接以佐证信息
      placeholder: 
    validations:
      required: true

  # 是否愿意提交 PR
  - type: dropdown
    id: canImplement
    attributes:
      label: 您愿意提交 PR 吗？
      description: 您是否愿意为此建议提交一个拉取请求（PR）？
      options:
        - '否'
        - '可能'
        - '是'
    validations:
      required: false

  # 确认复选框
  - type: checkboxes
    id: idiot-check
    attributes:
      label: 请勾选以下选项
      options:
        - label: 据我所知，我提供的信息是正确的
          required: true
        - label: 我已确认没有类似的问题被提出
          required: true
        - label: 我同意遵守本仓库的[行为准则](https://github.com/Lissy93/personal-security-checklist/blob/master/.github/CODE_OF_CONDUCT.md)
          required: true
